version: 2.1

orbs:
 #android: circleci/android@0.2.0
 android: circleci/android@0.5.17

jobs:
  build:
    #executor: android/android
    docker:
       - image: circleci/openjdk:11.0.3-jdk-stretch
       - image: circleci/android:api-28-alpha
    
    environment:
        JVM_OPTS: -Xmx3200m
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        Gradle_Home: /opt/android/android-studio/gradle/gradle-4.1
        
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching:true
      - restore_cache:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
              - ~/.gradle
          key: v1-{{checksum "build.gradle" }}-{{ checksum "android/build.gradle" }}
      - run: Run Tests
        name: Run Tests
        command: ./gradlew lint test
        
        #store test results
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_tests_results:
          path: app/build/test-results
